#!/bin/sh
streams=""
for stream in $(ls /tmp/); do
  if [[ -d /tmp/$stream ]]; then
    file="$(ls /tmp/$stream | head -1)"
    if [[ $file ]]; then
      path="/tmp/$stream/$file"
      echo "$path"
    fi
  else
    path="/tmp/$stream"
  fi
  if [[ $path ]]; then
    streams="$streams --stream pipe://$path?name=$stream";
    file=
    path=
  fi
done

echo "Starting snapcast server with streams $streams"
#snapserver --stream pipe:///tmp/snapfifo?name=default
snapserver $streams
