#!/bin/sh
streams=""
for stream in `ls /tmp/streams`; do
  streams="$streams --stream pipe:///tmp/$stream?name=$stream";
done

echo "Starting snapcast server..."
#snapserver --stream pipe:///tmp/snapfifo?name=default
snapserver $streams
